language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: ofPGe8bMhX/FJpUkcjI0K8vR/+nnCAGa8iWLfx5vUxqnYaQfeaHdvH/Bzz0/oZRiCkE6AD2qKsNZgyBv3KKexvUuqCPK8E952b6R/6ZzgHS7gXmidpPijisCjPD8A6Ly8Kr9imoVQPACUED6XqWL/nz6WM7BaLCjcjYHFrdzuzOEuKxynUEW7SChZm9ifsEIN4v8RtnZ8Z/9NFEByWFSRZMSariDYtItB9UcKcw2jzUIXhQM8++ImPr6OsHNTU41FaovespJSpwLmQpSzvfDQE+ha4NwcodTy8RwasSegoqSzZTGYjEjqdwnZZNzogbH6+ZND98uHU4RatV79uQmK5AWsHK+4P1bYh+w8DaoVjTLNF4d/C6OQlh/e+T9SPdtcu3US2rOTEKmvVCTMip6NauWIF0Z3QH8dn2g+c2NXW9eZ0zQ7wx3UqBChk+UQW6YIhV322cYxVX1rEyWVe/PDJvxR/HeGzRfYJJHvs18eXFzkndFN0eGgaPJr3dBNlsqQ3OQqGe/yeEFAKsjLI1UA9PSGgteWKOOEkCe5xAS8s4UeLIZmSiL2hpoE3KkQVwjVTFWylETwnqkOBEmkXWmYpgkMTL5nW+SJpk49tINDj2suNj+jRCbLbJ4uJ1sFdRnQa7rM6Pg2PI2nX+dBMpg7O5IT3D5K3XVGqA6l2j94u0=
